version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: django_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: django_web
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    command: >
      sh -c "python manage.py migrate &&
             gunicorn book_store.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - .:/app

  celery:
    build: .
    container_name: django_celery
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    command: celery -A book_store worker --loglevel=info --pool=solo
    depends_on:
      - redis
      - web
    volumes:
      - .:/app

  celery-beat:
    build: .
    container_name: django_celery_beat
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    command: celery -A book_store beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - redis
      - web
    volumes:
      - .:/app